### ISSUE TITLE
Arrays_Simulation_2D Arrays_Matrix Multiplication_Negative Size

### ISSUE THREAD

**Issue by kishansairam9** [virtual-labs-archive/computer-programming-responsive-iiith#316]
Defect Description : Matrix Dimensions are allowed to be inputted as negative values. No proper Input Validation

Steps to Reproduce : Visit [Simulation Page of 2D-Array](http://cse02-iiith.vlabs.ac.in/exp4/simulation/2-D/index.html) and input negative Dimensions to array size and the result is as follows.

![issue](https://user-images.githubusercontent.com/40003481/54488448-e89ff680-48c7-11e9-8f3d-4ede99a87a5a.gif)

**Comment by Akshat-Goyal** [comment]
fixed
commit id: 8d87d826f2adb258eb6fe6b5ee859f3aeed58e64

**Comment by DevikaBoddu** [comment]
Valid fix: @Akshat-Goyal
