### ISSUE TITLE
Arrays_Simulation_1D-Array_Fractional Input Array Size

### ISSUE THREAD

**Issue by kishansairam9** [virtual-labs-archive/computer-programming-responsive-iiith#317]
Defect Description : Fractional Array input sizes are allowed in experiment. Though inputting fractional values doesn't allow user to run the code as it shows No of input Values and Array Size don't match.

Steps to reproduce : Visit [Simulation Page of 1D-Arrays](http://cse02-iiith.vlabs.ac.in/exp4/simulation/1-D/index.html) and input a fractional value as array size and try to run it. It doesn't show proper error message indicating invalid input size

![image](https://user-images.githubusercontent.com/40003481/54488508-71b72d80-48c8-11e9-91b0-f9fed5fb9066.png)

**Comment by chinnusai25** [comment]
Issue on Fractional value input is RESOLVED!!!!
Commit id -- # 8177d04

**Comment by DevikaBoddu** [comment]
Valid fix: @chinnusai25
