### ISSUE TITLE
Strings_String Comparision Simulation_Scanning Strings with spaces in C

### ISSUE THREAD

**Issue by kishansairam9** [virtual-labs-archive/computer-programming-responsive-iiith#345]
Defect Description : In C, when strings which have spaces are scanned, only the value till the first space is scanned and rest is neglected. This simulation doesn't take this into account. When the code is run on pc. It behaves differently.

Steps to reproduce : Visit [String Comparision Simulation](http://cse02-iiith.vlabs.ac.in/exp7/simulation/StringComparison/index.html) and give one input string without spaces and other with spaces but part of string before first space is same as the other string. 

Expected Output : Input Str 1 = 'abc abc' Str 2= 'abc' , OUTPUT is both are equal
Actual Output : Str1 is  greater than Str2

Input :  
![image](https://user-images.githubusercontent.com/40003481/54489899-35d79480-48d7-11e9-8953-4854232c810f.png)

Output :
![image](https://user-images.githubusercontent.com/40003481/54489989-037a6700-48d8-11e9-992e-a631ecac4aa3.png)

**Comment by Akshat-Goyal** [comment]
fixed
commit id: c8d1a6e412514e0a5e03ea6b47bf36806f1f65db

**Comment by DevikaBoddu** [comment]
Valid fix: @Akshat-Goyal
